#!/bin/bash
# Setup script for PhotoMap Analytics & Monitoring

echo "🚀 Setting up analytics infrastructure for PhotoMap..."

# 1. Apply the database migration
echo ""
echo "📊 Step 1: Deploying Supabase migration (email + monitoring tables)..."
echo "Run this in Supabase dashboard (SQL editor) or via CLI:"
echo ""
echo "supabase db push --project-ref <YOUR_PROJECT_REF>"
echo ""
echo "Or paste migrations/002_add_email_and_monitoring.sql into Supabase SQL editor"

# 2. Update Supabase types
echo ""
echo "📋 Step 2: Updating TypeScript types..."
echo "Update src/integrations/supabase/types.ts with new tables:"
echo "- activity_logs"
echo "- app_metrics"
echo "- error_logs"
echo "- feature_usage"
echo "- storage_usage"
echo ""
echo "Run: supabase gen types typescript --project-ref <YOUR_PROJECT_REF> > src/integrations/supabase/types.ts"

# 3. Dashboard setup instructions
echo ""
echo "📈 Step 3: Setting up monitoring dashboards..."
echo ""
echo "OPTION A: Supabase Studio (Built-in)"
echo "1. Go to your Supabase project dashboard"
echo "2. Create a new SQL query for each view:"
echo ""
echo "  -- Daily Active Users"
echo "  SELECT * FROM public.daily_active_users_view LIMIT 30;"
echo ""
echo "  -- Subscription Revenue"
echo "  SELECT * FROM public.subscription_revenue_view;"
echo ""
echo "  -- Top Features Used"
echo "  SELECT feature_name, COUNT(*) as usage_count, MAX(last_used_at) as latest"
echo "  FROM feature_usage"
echo "  GROUP BY feature_name"
echo "  ORDER BY usage_count DESC;"
echo ""
echo "  -- Recent Errors"
echo "  SELECT * FROM error_logs ORDER BY created_at DESC LIMIT 50;"
echo ""

echo "OPTION B: Grafana (Advanced)"
echo "1. Install Grafana: https://grafana.com/grafana/download"
echo "2. Add Supabase as PostgreSQL data source:"
echo "   - Host: <PROJECT_ID>.supabase.co"
echo "   - Database: postgres"
echo "   - User: postgres"
echo "   - Password: <YOUR_PASSWORD>"
echo "   - SSL Mode: require"
echo "3. Create dashboards from the views above"
echo ""

echo "OPTION C: Metabase (Easiest)"
echo "1. Sign up at https://www.metabase.com/ (free tier available)"
echo "2. Connect your Supabase database:"
echo "   - Host: <PROJECT_ID>.supabase.co"
echo "   - Port: 5432"
echo "   - Database: postgres"
echo "   - User: postgres"
echo "3. Create questions from activity_logs, app_metrics, feature_usage tables"
echo "4. Build dashboards for DAU, feature adoption, revenue"
echo ""

# 4. Analytics implementation status
echo ""
echo "✅ Analytics Implementation Status:"
echo ""
echo "Components with analytics:"
echo "  ✓ PhotoUploader - tracks photo uploads with file sizes"
echo "  ✓ PhotoMap - tracks map views and style changes"
echo "  ✓ UpgradeModal - tracks upgrade view and completion"
echo "  ✓ MetadataEditor - tracks metadata edits"
echo "  ✓ PhotoGallery - tracks photo views"
echo "  ✓ Header - tracks login/logout"
echo "  ✓ Auth page - tracks signup/signin with errors"
echo "  ✓ Index page - tracks page navigation"
echo ""

# 5. Test analytics
echo ""
echo "🧪 Step 4: Testing analytics..."
echo "1. Start the app: npm run dev"
echo "2. Perform these actions and check activity_logs table:"
echo "   - Upload a photo (should log photo_upload)"
echo "   - View the map (should log map_view)"
echo "   - Change map style (should log map_style_change and feature use)"
echo "   - Open upgrade modal (should log upgrade_view)"
echo "   - Click metadata editor (should log metadata_editor feature use)"
echo ""
echo "Query to verify: SELECT * FROM activity_logs ORDER BY created_at DESC LIMIT 20;"
echo ""

# 6. Alerts & Monitoring
echo ""
echo "🚨 Step 5: Setting up alerts..."
echo ""
echo "Critical alerts to implement:"
echo "1. Error spike: > 10 errors in 5 minutes"
echo "   - Slack/PagerDuty integration"
echo "   - Monitor: SELECT COUNT(*) FROM error_logs WHERE created_at > NOW() - INTERVAL '5 min' AND severity = 'critical';"
echo ""
echo "2. Service down: 0 DAU for 15 minutes"
echo "   - SELECT COUNT(DISTINCT user_id) FROM activity_logs WHERE created_at > NOW() - INTERVAL '15 min';"
echo ""
echo "3. Storage quota: User exceeds 80% of limit"
echo "   - Monitor: SELECT * FROM storage_usage WHERE (total_bytes / MAX_STORAGE_BYTES) > 0.8;"
echo ""

echo ""
echo "🎉 Analytics setup complete!"
echo ""
echo "Next steps:"
echo "1. Deploy the migration"
echo "2. Update TypeScript types"
echo "3. Choose a dashboard tool (Supabase/Grafana/Metabase)"
echo "4. Test analytics end-to-end"
echo "5. Set up critical alerts"
echo ""
